import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import NavLinks from '@/app/ui/records/nav-links';
import clsx from 'clsx';

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Six Questions",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className} antialiased`}>
        <div className="flex md:flex-row flex-col m-2">
          <div className={clsx("flex flex-row md:flex-col md:basis-48 mt-6 " +
                               "shrink-0 space-x-2 p-2 md:space-x-0 md:space-y-4")}><NavLinks /></div>
          <div className="flex-col w-full">{children}</div>
          {/*
          <div className="flex md:basis-40 shrink-0 md:flex-row flex-col"><SideNav /></div>
          <div className="flex-col">{children}</div>
          */}
        </div>
      </body>
    </html>
  );
}
