import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "@/app/globals.css";
import NavLinks from '@/app/ui/records/nav-links';
import clsx from 'clsx';

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Six Questions",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <div className="flex md:flex-row flex-col min-h-screen mx-2">
      <div className={clsx("flex flex-row md:flex-col md:basis-48 mt-6 " +
                            "shrink-0 space-x-2 py-2 md:space-x-0 md:space-y-4")}><NavLinks /></div>
      <div className="flex-col w-full">{children}</div>
    </div>
  );
}
